--- 
#user: jhoglund
cwd: /Users/jhoglund/SWATprojects/Stixy/stixy_trunk
log_file: log/mongrel.log
port: "8000"
environment: development
#group: www
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 4