class UpdateUsers < ActiveRecord::Migration
  def self.up
    [ { :login => "claes_huber@swatdesign.com",       :update_data => { :address => "c/o Cabesa, Kronobergsgatan 21",  :city => "Stockholm",      :state => nil,  :zip => "112 33",     :country => nil,        :phone => "6505127",          :mobile_phone => "4912348",          :description => "This is a small message from me to you." }},
      { :login => "peter_ekman@swatdesign.com",       :update_data => { :address => "1299 4th Street",                 :city => "San Rafael",     :state => "CA", :zip => "94901",      :country => "USA",      :phone => nil,                :mobile_phone => "415.823.1340",     :description => "This is a small message from me to you." }},
      { :login => "andreas_gronqvist@swatdesign.com", :update_data => { :address => "Sveavägen 98 6tr",                :city => "Stockholm",      :state => nil,  :zip => "11350",      :country => nil,        :phone => "153124",           :mobile_phone => "167263",           :description => "This is a small message from me to you." }},
      { :login => "jonas@swatdesign.com",             :update_data => { :address => "Genvägen 9",                      :city => "Karlshamn",      :state => nil,  :zip => "374 37",     :country => "Sweden",   :phone => nil,                :mobile_phone => "962263",           :description => "This is a small message from me to you." }},
      { :login => "maria_distner@swatdesign.com",     :update_data => { :address => "Genvägen 9",                      :city => "Karlshamn",      :state => nil,  :zip => nil,          :country => nil,        :phone => "11183",            :mobile_phone => "962063",           :description => "This is a small message from me to you." }},
      { :login => "mathias_worbin@swatdesign.com",    :update_data => { :address => "Box 702",                         :city => "Ölmhult",        :state => nil,  :zip => "34381",      :country => "Sweden",   :phone => "133298",           :mobile_phone => "653027",           :description => "This is a small message from me to you." }},
      { :login => "karin_lilja@swatdesign.com",       :update_data => { :address => "Thornbergsgatan 6",               :city => "Höör",           :state => nil,  :zip => "243 30",     :country => nil,        :phone => "0413 225 87",      :mobile_phone => "0708-50 83 65",    :description => "This is a small message from me to you." }},
      { :login => "mats_sjoholm@swatdesign.com",      :update_data => { :address => "Ronnebygatan 13",                 :city => "Karlshamn",      :state => nil,  :zip => "374 35",     :country => nil,        :phone => nil,                :mobile_phone => "0708-882110",      :description => "This is a small message from me to you." }},
      { :login => "stefan_fohlin@swatdesign.com",     :update_data => { :address => "Erik Dahlbergsvägen 71",          :city => "Karlshamn",      :state => nil,  :zip => "374 39",     :country => "Sverige",  :phone => "18202",            :mobile_phone => "178611",           :description => "This is a small message from me to you." }},
      { :login => "conny_rikardsson@swatdesign.com",  :update_data => { :address => "Erik Håkansväg 8",                :city => "Åhus",           :state => nil,  :zip => "296 38",     :country => nil,        :phone => "240024",           :mobile_phone => nil,                :description => "This is a small message from me to you." }},
      { :login => "svante_selling@swatdesign.com",    :update_data => { :address => "Box 19176",                       :city => "Stockholm",      :state => nil,  :zip => "104 32",     :country => nil,        :phone => "+46 8 646 65 12",  :mobile_phone => "+46 708 83 08 08", :description => "This is a small message from me to you." }},
      { :login => "svante_rodegard@swatdesign.com",   :update_data => { :address => "P.O.Box 8067",                    :city => "Emeryville.",    :state => "CA", :zip => "94662-0067", :country => "USA",      :phone => nil,                :mobile_phone => "1-415-810-0910",   :description => "This is a small message from me to you." }},
      { :login => "tom_friesch@swatdesign.com",       :update_data => { :address => "341 Maple Street",                :city => "San Francisco",  :state => "CA", :zip => "94118",      :country => "USA",      :phone => "3860913",          :mobile_phone => nil,                :description => "This is a small message from me to you." }}
		].each do |data|
		  User.find_by_login(data[:login]).update_attributes!(data[:update_data])
	  end
	end
end