class TimeZones
  ZONES = [[-12,	"Baker Island, Howland Island"],
          [-11,	"American Samoa, Midway Atoll, Samoa"],
          [-10,	"Cook Islands, French Polynesia, United States (HST)"],
          [-9,	"United States (AKST)"],
          [-8,	"Canada (PST—Pacific Standard Time), Mexico, United States (PST)"],
          [-7,	"Canada (MST—Mountain Standard Time), Mexico, United States (MST)"],
          [-6,	"Canada (CST—Central Standard Time), Mexico, United States (CST)"],
          [-5,	"Brazil, Canada (EST—Eastern Standard Time), United States (EST)"],
          [-4,	"Brazil, Canada (AST—Atlantic Standard Time)"],
          [-3,	"Argentina, Brazil"],
          [-2,	"Brazil - Ocean Islands, South Georgia"],
          [-1,	"Cape Verde, Portugal"],
          [0,	"Iceland, Ireland, Portugal, Spain, United Kingdom (GMT / BST)"],
          [1,	"Austria, Denmark, France, Germany, Netherlands, Norway, Spain, Sweden"],
          [2,	"Bulgaria, Egypt, Estonia, Finland, Israel, Russia, South Africa"],
          [3,	"Iraq, Kenya, Kuwait, Russia* (Moscow, St. Petersburg), Saudi Arabia"],
          [3.5,	"Iran"],
          [4,	"Russia, United Arab Emirates"],
          [4.5,	"Afghanistan"],
          [5,	"Pakistan (PST— Pakistan Standard Time), Russia"],
          [5.5,	"India (IST—Indian Standard Time), Sri Lanka"],
          [5.75,	"Nepal"],
          [6,	"Bangladesh, Russia"],
          [7,	"Indonesia (WIB), Russia, Thailand"],
          [8,	"Australia (AWST), China, Indonesia (WITA), Philippines, Russia"],
          [8.75,	"Western Australia"],
          [9,	"Indonesia (WIT), Japan (JST), South Korea (KST), Russia"],
          [9.5,	"Australia (ACST)"],
          [10,	"Australia (AEST), Russia"],
          [10.5,	"Australia (New South Wales)"],
          [11,	"Russia, Solomon Islands"],
          [12,	"Fiji, New Zealand, Russia"]]
          
					# "(GMT -12:00) International Date Line West"],
					# "(GMT -11:00) Midway Island, Samoa"],
					# "(GMT -10:00) Hawaii"],
					# "(GMT -09:00) Alaska"],
					# "(GMT -08:00) Pacific Time (United States &amp; Canada), Tijuana"],
					# "(GMT -07:00) Arizona"],
					# "(GMT -07:00) Chihuahua, La Paz, Mazatlan"],
					# "(GMT -07:00) Mountain Time (United States &amp; Canada)"],
					# "(GMT -06:00) Central America"],
					# "(GMT -06:00) Central Time (United States &amp; Canada)"],
					# "(GMT -06:00) Guadalajara, Mexico City, Monterrey"],
					# "(GMT -06:00) Saskatchewan"],
					# "(GMT -05:00) Bogota, Lima, Quito"],
					# "(GMT -05:00) Eastern Time (United States &amp; Canada)"],
					# "(GMT -05:00) Indiana (East)"],
					# "(GMT -04:00) Atlantic Time (Canada)"],
					# "(GMT -04:00) Caracas, La Paz"],
					# "(GMT -04:00) Santiago"],
					# "(GMT -03:30) Newfoundland"],
					# "(GMT -03:00) Brasilia"],
					# "(GMT -03:00) Buenos Aires, Georgetown"],
					# "(GMT -03:00) Greenland"],
					# "(GMT -02:00) Mid-Atlantic"],
					# "(GMT -01:00) Azores"],
					# "(GMT -01:00) Cape Verde Island"],
					# "(GMT  00:00) Casablanca, Monrovia"],
					# "(GMT  00:00) Greenwich Mean Time: Dublin, Edinburgh"],
					# "(GMT +01:00) Amsterdam, Berlin, Bern, Rome, Stockholm"],
					# "(GMT +01:00) Belgrade, Bratislava, Budapest, Ljubljana"],
					# "(GMT +01:00) Brussels, Copenhagen, Madrid, Paris"],
					# "(GMT +01:00) Sarajevo, Skopje, Warsaw, Zagreb"],
					# "(GMT +01:00) West Central Africa"],
					# "(GMT +02:00) Athens, Istanbul, Minsk"],
					# "(GMT +02:00) Bucharest"],
					# "(GMT +02:00) Cairo"],
					# "(GMT +02:00) Harare, Pretoria"],
					# "(GMT +02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn"],
					# "(GMT +02:00) Jerusalem"],
					# "(GMT +03:00) Baghdad"],
					# "(GMT +03:00) Kuwait, Riyadh"],
					# "(GMT +03:00) Moscow, St. Petersburg, Volgograd"],
					# "(GMT +03:00) Nairobi"],
					# "(GMT +03:30) Tehran"],
					# "(GMT +04:00) Abu Dhabi, Muscat"],
					# "(GMT +04:00) Baku, Tbilisi, Yerevan"],
					# "(GMT +04:30) Kabul"],
					# "(GMT +05:00) Ekaterinburg"],
					# "(GMT +05:00) Islamabad, Karachi, Tashkent"],
					# "(GMT +05:30) Chennai, Kolkata, Mumbai, New Delhi"],
					# "(GMT +05:45) Kathmandu"],
					# "(GMT +06:00) Almaty, Novosibirsk"],
					# "(GMT +06:00) Astana, Dhaka"],
					# "(GMT +06:00) Sri Jayawardenepura"],
					# "(GMT +06:30) Rangoon"],
					# "(GMT +07:00) Bangkok, Hanoi, Jakarta"],
					# "(GMT +07:00) Krasnoyarsk"],
					# "(GMT +08:00) Beijing, Chongqing, Hong Kong, Urumqi"],
					# "(GMT +08:00) Irkutsk, Ulaan Bataar"],
					# "(GMT +08:00) Kuala Lumpur, Singapore"],
					# "(GMT +08:00) Perth"],
					# "(GMT +08:00) Taipei"],
					# "(GMT +09:00) Osaka, Sapporo, Tokyo"],
					# "(GMT +09:00) Seoul"],
					# "(GMT +09:00) Yakutsk"],
					# "(GMT +09:30) Adelaide"],
					# "(GMT +09:30) Darwin"],
					# "(GMT +10:00) Brisbane"],
					# "(GMT +10:00) Canberra, Melbourne, Sydney"],
					# "(GMT +10:00) Guam, Port Moresby"],
					# "(GMT +10:00) Hobart"],
					# "(GMT +10:00) Vladivostok"],
					# "(GMT +11:00) Magadan, Solomon Island, New Caledonia"],
					# "(GMT +12:00) Auckland, Wellington"],
					# "(GMT +12:00) Fiji, Kamchatka, Marshall Island"],
					# "(GMT +13:00) Nuku'alofa"]

          
end